name: Bug Report
description: If you would like to report an issue to Maven Central utility plugins for Gradle, please use this template.

body:
- type: checkboxes
  attributes:
    label: Check Ahead
    options:
    - label: >
        I have searched the [issues](https://github.com/YongGoose/Maven-Central-utility-plugins-for-Gradle/issues) of this repository and believe that this is not a duplicate.
      required: true

- type: textarea
  attributes:
    label: Ⅰ. Issue Description
  validations:
    required: false

- type: textarea
  attributes:
    label: Ⅱ. Describe what happened
    placeholder: >
      If there is an exception, please attach the exception trace:
      
      ```
      Just paste your stack trace here!
      ```
  validations:
    required: false

- type: textarea
  attributes:
    label: Ⅲ. Describe what you expected to happen
  validations:
    required: false

- type: textarea
  attributes:
    label: Ⅳ. How to reproduce it (as minimally and precisely as possible)
    placeholder: >
      1. xxx
      2. xxx
      3. xxx

      Minimal yet complete reproducer code (or URL to code):
  validations:
    required: false

- type: textarea
  attributes:
    label: Ⅴ. Anything else we need to know?
  validations:
    required: false
