name: Feature Request
description: Suggest an idea for kotlin-pom-gradle

body:
- type: textarea
  attributes:
    label: Why you need it?
    description: Is your feature request related to a problem? Please describe in details

- type: textarea
  attributes:
    label: How it could be?
    description: A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

- type: textarea
  attributes:
    label: Other related information
    description: Add any other context or screenshots about the feature request here.
  
